import { collection, getDocs, query, where } from 'firebase/firestore';
import { db, firebaseEnabled } from './firebase';

const openGallery = async (image, name) => {
  const card = image.closest('.food-card'); let urls = [image.currentSrc || image.src];
  if (firebaseEnabled && db) { try { const slug = location.pathname.split('/').filter(Boolean).pop(); const stores = await getDocs(query(collection(db, 'stores'), where('slug', '==', slug))); if (!stores.empty) { const docs = await getDocs(collection(db, 'stores', stores.docs[0].id, 'menuItems')); const item = docs.docs.map((d) => d.data()).find((data) => data.name === name); if (item?.imageUrls?.length) urls = item.imageUrls; } } catch { /* primary image remains available */ } }
  let index = 0; const modal = document.createElement('div'); modal.className='gallery-modal-backdrop'; modal.innerHTML=`<section class="gallery-modal" role="dialog" aria-modal="true" aria-label="Galeria de ${name}"><button class="gallery-close" aria-label="Fechar">×</button><button class="gallery-prev" aria-label="Imagem anterior">‹</button><img class="gallery-image" src="${urls[0]}" alt="${name}"><button class="gallery-next" aria-label="Próxima imagem">›</button><p class="gallery-caption">${name} <span>1/${urls.length}</span></p></section>`; document.body.appendChild(modal); const view=modal.querySelector('.gallery-image'); const counter=modal.querySelector('.gallery-caption span'); const render=()=>{view.src=urls[index];counter.textContent=`${index+1}/${urls.length}`}; modal.querySelector('.gallery-close').onclick=()=>modal.remove(); modal.onmousedown=(e)=>{if(e.target===modal)modal.remove()}; modal.querySelector('.gallery-prev').onclick=()=>{index=(index-1+urls.length)%urls.length;render()}; modal.querySelector('.gallery-next').onclick=()=>{index=(index+1)%urls.length;render()};
};
document.addEventListener('click',(event)=>{const image=event.target.closest('.food-card > img');if(!image)return;event.preventDefault();openGallery(image,image.closest('.food-card').querySelector('h3')?.textContent?.trim()||'Prato');});
