import { addDoc, collection, getDocs, query, serverTimestamp, where } from 'firebase/firestore';
import { db, firebaseEnabled } from './firebase';

const safe = (v) => String(v).replace(/[&<>"']/g, (c) => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' }[c]));
const openOrder = (anchor) => {
  if (document.querySelector('.order-modal-backdrop')) return;
  const phone = new URL(anchor.href).pathname.replaceAll('/', '');
  const brand = document.querySelector('.brand span:last-child')?.textContent?.trim() || 'nossa loja';
  const items = [...document.querySelectorAll('.food-card')].map((card) => ({ name: card.querySelector('h3')?.textContent?.trim() || 'Item', price: card.querySelector('.food-bottom b')?.textContent?.trim() || '' }));
  const el = document.createElement('div'); el.className='order-modal-backdrop'; el.innerHTML=`<section class="order-modal" role="dialog" aria-modal="true" aria-labelledby="order-title"><button class="modal-close" aria-label="Fechar">×</button><div class="order-form-view"><p class="eyebrow">PEDIDO PELO WHATSAPP</p><h2 id="order-title">Vamos anotar seu pedido</h2><p class="order-intro">Escolha os pratos e conte onde devemos entregar.</p><form id="order-form"><div class="order-items">${items.map((x,i)=>`<label class="order-item"><span><input type="number" min="0" max="20" value="0" data-item="${i}"><b>${safe(x.name)}</b><small>${safe(x.price)}</small></span><strong>quantidade</strong></label>`).join('')}</div><div class="order-fields"><input required name="name" placeholder="Seu nome" autocomplete="name"><input required name="phone" placeholder="Seu telefone" autocomplete="tel"><input required name="address" placeholder="Endereço de entrega" autocomplete="street-address"><textarea name="notes" rows="3" placeholder="Observações (referência, preferências...)" ></textarea></div><button class="button primary order-submit">Salvar pedido e enviar</button><button class="location-button" type="button" id="get-location">⌖ Adicionar minha localização atual</button><p class="location-status" id="location-status">A localização só será compartilhada se você autorizar.</p></form></div><div class="order-success" hidden><div class="success-mark">✓</div><h2>Seu pedido já foi anotado.</h2><p>Agora é só aguardar a confirmação pelo WhatsApp. Obrigado por escolher a ${safe(brand)}!</p><button class="button primary close-success" type="button">Voltar para o cardápio</button></div></section>`;
  document.body.appendChild(el); let mapsUrl=''; const close=()=>el.remove(); el.querySelector('.modal-close').onclick=close; el.querySelector('.close-success').onclick=close; el.onmousedown=(e)=>{if(e.target===el)close()};
  el.querySelector('#get-location').onclick=()=>{const status=el.querySelector('#location-status'); if(!navigator.geolocation){status.textContent='Seu navegador não oferece localização automática.';return;} status.textContent='Buscando sua localização…'; navigator.geolocation.getCurrentPosition(p=>{mapsUrl=`https://maps.google.com/?q=${p.coords.latitude},${p.coords.longitude}`;status.textContent='Localização adicionada ao pedido ✓'},()=>{status.textContent='Não foi possível obter a localização.'},{enableHighAccuracy:true,timeout:10000});};
  el.querySelector('#order-form').onsubmit=async(e)=>{e.preventDefault();const form=new FormData(e.currentTarget);const chosen=[...el.querySelectorAll('[data-item]')].map((input,i)=>({...items[i],quantity:Number(input.value)})).filter(x=>x.quantity>0);if(!chosen.length){el.querySelector('.order-intro').textContent='Escolha pelo menos um prato para continuar.';return;}const button=el.querySelector('.order-submit');button.disabled=true;button.textContent='Salvando pedido…';const order={storeSlug:location.pathname.split('/').filter(Boolean).pop()||'',items:chosen,customer:{name:form.get('name'),phone:form.get('phone')},address:form.get('address'),notes:form.get('notes')||'',mapsUrl,status:'new',createdAt:serverTimestamp()};try{if(firebaseEnabled&&db){const stores=await getDocs(query(collection(db,'stores'),where('slug','==',order.storeSlug)));if(stores.empty)throw new Error('Loja não encontrada.');await addDoc(collection(db,'stores',stores.docs[0].id,'orders'),order);}const lines=chosen.map(x=>`• ${x.quantity}x ${x.name} (${x.price})`).join('\\n');const text=`Olá, ${brand}! Gostaria de fazer um pedido:\\n\\n${lines}\\n\\nCliente: ${form.get('name')}\\nTelefone: ${form.get('phone')}\\nEndereço: ${form.get('address')}${form.get('notes')?`\\nObservações: ${form.get('notes')}`:''}${mapsUrl?`\\nLocalização no Maps: ${mapsUrl}`:''}`;window.open(`https://wa.me/${phone}?text=${encodeURIComponent(text)}`,'_blank','noopener,noreferrer');el.querySelector('.order-form-view').hidden=true;el.querySelector('.order-success').hidden=false;}catch(err){el.querySelector('#location-status').textContent=`Não foi possível salvar o pedido: ${err.message}`;button.disabled=false;button.textContent='Salvar pedido e enviar';}};
};
document.addEventListener('click',(e)=>{const a=e.target.closest('a[href^="https://wa.me/"]');if(!a||a.classList.contains('contact-fab')||!/(fazer pedido|pedir pelo whatsapp)/i.test(a.textContent||''))return;e.preventDefault();openOrder(a);});
