import { addDoc, collection, getDocs, query, serverTimestamp, where } from 'firebase/firestore';
import { db, firebaseEnabled } from './firebase';
import QRCode from 'qrcode';

const safe = (v) => String(v).replace(/[&<>"']/g, (c) => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' }[c]));
const parsePrice = (value) => Number(String(value || '').replace(/R\$\s?/gi, '').replace(/\s/g, '').replace(/\./g, '').replace(',', '.')) || 0;
const formatPrice = (value) => new Intl.NumberFormat('pt-BR', { style:'currency', currency:'BRL' }).format(value);
const pixText=(value,max)=>String(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9 .]/g,'').toUpperCase().slice(0,max);
const pixField=(id,value)=>`${id}${String(value.length).padStart(2,'0')}${value}`;
const pixCrc=payload=>{let crc=0xffff;for(let index=0;index<payload.length;index++){crc^=payload.charCodeAt(index)<<8;for(let bit=0;bit<8;bit++)crc=crc&0x8000?((crc<<1)^0x1021)&0xffff:(crc<<1)&0xffff;}return crc.toString(16).toUpperCase().padStart(4,'0');};
const pixPayload=({key,name,city,amount})=>{const merchant=pixField('00','br.gov.bcb.pix')+pixField('01',String(key).trim());const base=pixField('00','01')+pixField('01','12')+pixField('26',merchant)+pixField('52','0000')+pixField('53','986')+pixField('54',Number(amount).toFixed(2))+pixField('58','BR')+pixField('59',pixText(name,25)||'RESTAURANTE')+pixField('60',pixText(city,15)||'BRASIL')+pixField('62',pixField('05','***'))+'6304';return base+pixCrc(base);};
const orderMessage = ({ brand, chosen, name, phone, address, notes, mapsUrl }) => {
  const itemLines = chosen.map((item) => {
    const subtotal = parsePrice(item.price) * item.quantity;
    return `• ${item.quantity}x ${item.name} — ${formatPrice(subtotal)}`;
  }).join('\n');
  const total = chosen.reduce((sum, item) => sum + parsePrice(item.price) * item.quantity, 0);
  return `🍽️ *NOVO PEDIDO — ${brand.toUpperCase()}*\n\n📋 *ITENS DO PEDIDO*\n${itemLines}\n\n💰 *TOTAL DO PEDIDO: ${formatPrice(total)}*\n\n👤 *CLIENTE*\n${name}\n📞 ${phone}\n\n📍 *ENDEREÇO DE ENTREGA*\n${address}${notes ? `\n\n📝 *OBSERVAÇÕES*\n${notes}` : ''}\n\n🗺️ *LOCALIZAÇÃO NO MAPA*\n${mapsUrl}\n\n✅ Pedido enviado pelo Cardápio do Dia.`;
};
const openOrder = (anchor) => {
  if (document.querySelector('.order-modal-backdrop')) return;
  const phone = new URL(anchor.href).pathname.replaceAll('/', '');
  const pixKey = anchor.dataset.pixKey?.trim() || '';
  const storeId = anchor.dataset.storeId?.trim() || '';
  let payment = {}; try { payment=JSON.parse(anchor.dataset.payment || '{}'); } catch {}
  const storeSlug = anchor.dataset.storeSlug?.trim() || location.pathname.split('/').filter(Boolean).pop() || '';
  const isPreview = Boolean(anchor.closest('.preview'));
  const brand = document.querySelector('.brand span:last-child')?.textContent?.trim() || 'nossa loja';
  const items = [...document.querySelectorAll('.food-card')].map((card) => ({ id:card.dataset.itemId, name: card.querySelector('h3')?.textContent?.trim() || 'Item', price: card.querySelector('.food-bottom b')?.textContent?.trim() || '' }));
  const digitalPayments=Boolean(storeId&&firebaseEnabled&&!isPreview); const stripeEnabled=Boolean(payment.stripeConnected||payment.stripeAccountId);
  const el = document.createElement('div'); el.className='order-modal-backdrop'; el.innerHTML=`<section class="order-modal" role="dialog" aria-modal="true" aria-labelledby="order-title"><button class="modal-close" aria-label="Fechar">×</button><div class="order-form-view"><p class="eyebrow">FAZER PEDIDO</p><h2 id="order-title">Vamos anotar seu pedido</h2><p class="order-intro">Escolha os pratos, a entrega e como deseja pagar.</p><form id="order-form"><div class="order-items">${items.map((x,i)=>`<label class="order-item"><span><input type="number" min="0" max="20" value="0" data-item="${i}"><b>${safe(x.name)}</b><small>${safe(x.price)}</small></span><strong>quantidade</strong></label>`).join('')}</div><div class="order-fields"><input required name="name" placeholder="Seu nome" autocomplete="name"><input required type="email" name="email" placeholder="Seu e-mail" autocomplete="email"><input required name="phone" placeholder="Seu telefone" autocomplete="tel"><input required name="address" placeholder="Endereço de entrega" autocomplete="street-address"><textarea name="notes" rows="3" placeholder="Observações (referência, preferências...)"></textarea></div><fieldset class="payment-options"><legend>Como deseja concluir?</legend>${digitalPayments&&payment.enabled&&pixKey?'<label><input type="radio" name="method" value="pix"> Pix com QR Code</label>':''}${digitalPayments&&stripeEnabled?'<label><input type="radio" name="method" value="stripe"> Cartão à vista</label>':''}${digitalPayments?'<label><input type="radio" name="method" value="delivery"> Pagar na entrega</label>':''}<label><input type="radio" name="method" value="whatsapp" checked> Combinar pelo WhatsApp</label></fieldset><button class="button primary order-submit">Continuar pedido</button><button class="location-button" type="button" id="get-location">⌖ Adicionar minha localização atual</button><p class="location-status" id="location-status">A localização só será compartilhada se você autorizar.</p></form></div><div class="order-success" hidden><div class="success-mark">✓</div><h2>Seu pedido já foi anotado.</h2><p>Agora é só aguardar a confirmação. Obrigado por escolher a ${safe(brand)}!</p><div class="pix-payment" hidden><p class="eyebrow">PAGAMENTO POR PIX</p><img class="pix-qr" alt="QR Code Pix"><div class="pix-key"><code></code><button class="copy-pix" type="button">Copiar Pix</button></div><small class="pix-copy-status" aria-live="polite"></small></div><button class="button primary close-success" type="button">Voltar para o cardápio</button></div></section>`;
  document.body.appendChild(el); let mapsUrl=''; const close=()=>el.remove(); el.querySelector('.modal-close').onclick=close; el.querySelector('.close-success').onclick=close; el.onmousedown=(e)=>{if(e.target===el)close()};
  const copyPix = el.querySelector('.copy-pix'); if (copyPix) copyPix.onclick=async()=>{const code=el.querySelector('.pix-key code').textContent;const status=el.querySelector('.pix-copy-status');try{await navigator.clipboard.writeText(code);status.textContent='Código Pix copiado!';copyPix.textContent='Copiado ✓';}catch{status.textContent='Não foi possível copiar. Selecione o código manualmente.';}};
  el.querySelector('#get-location').onclick=()=>{const status=el.querySelector('#location-status'); if(!navigator.geolocation){status.textContent='Seu navegador não oferece localização automática.';return;} status.textContent='Buscando sua localização…'; navigator.geolocation.getCurrentPosition(p=>{mapsUrl=`https://maps.google.com/?q=${p.coords.latitude},${p.coords.longitude}`;status.textContent='Localização adicionada ao pedido ✓'},()=>{status.textContent='Não foi possível obter a localização.'},{enableHighAccuracy:true,timeout:10000});};
  el.querySelector('#order-form').onsubmit=async(e)=>{e.preventDefault();const form=new FormData(e.currentTarget);const chosen=[...el.querySelectorAll('[data-item]')].map((input,i)=>({...items[i],quantity:Number(input.value)})).filter(x=>x.quantity>0);if(!chosen.length){el.querySelector('.order-intro').textContent='Escolha pelo menos um prato para continuar.';return;}const button=el.querySelector('.order-submit');button.disabled=true;button.textContent='Registrando pedido…';const address=String(form.get('address')||'');const fallbackMaps=`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(address)}`;const finalMapsUrl=mapsUrl||fallbackMaps;const customer={name:form.get('name'),email:form.get('email'),phone:form.get('phone')};const method=form.get('method');const apiItems=chosen.map(item=>({id:item.id,quantity:item.quantity}));const order={storeSlug,items:chosen,customer,address,notes:form.get('notes')||'',mapsUrl:finalMapsUrl,status:'new',createdAt:serverTimestamp()};const text=orderMessage({brand,chosen,name:customer.name,phone:customer.phone,address,notes:form.get('notes'),mapsUrl:finalMapsUrl});const whatsappUrl=`https://wa.me/${phone}?text=${encodeURIComponent(text)}`;try{if(method==='stripe'){const response=await fetch('/.netlify/functions/create-store-checkout',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({storeId,items:apiItems,customer})});const result=await response.json();if(!response.ok)throw new Error(result.error);location.href=result.checkoutUrl;return;}if(method==='pix'||method==='delivery'){const response=await fetch(`/.netlify/functions/${method==='pix'?'create-pix-order':'create-delivery-order'}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({storeId,items:apiItems,customer})});const result=await response.json();if(!response.ok)throw new Error(result.error);if(method==='pix'){const payload=pixPayload({key:pixKey,name:payment.pixReceiverName||brand,city:payment.pixCity,amount:result.total});el.querySelector('.pix-payment').hidden=false;el.querySelector('.pix-key code').textContent=payload;el.querySelector('.pix-qr').src=await QRCode.toDataURL(payload,{width:260,margin:2});}}else if(firebaseEnabled&&db&&!isPreview){const stores=await getDocs(query(collection(db,'stores'),where('slug','==',order.storeSlug)));if(stores.empty)throw new Error('Loja não encontrada.');await addDoc(collection(db,'stores',stores.docs[0].id,'orders'),order);window.open(whatsappUrl,'_blank','noopener');}el.querySelector('.order-form-view').hidden=true;el.querySelector('.order-success').hidden=false;}catch(err){el.querySelector('#location-status').textContent=`Não foi possível salvar o pedido: ${err.message}`;button.disabled=false;button.textContent='Continuar pedido';}};
};
document.addEventListener('click',(e)=>{const a=e.target.closest('a[href^="https://wa.me/"]');if(!a||a.classList.contains('contact-fab')||!/(fazer pedido|pedir pelo whatsapp)/i.test(a.textContent||''))return;e.preventDefault();openOrder(a);});

const setupItemSelect = (modal) => { const rows=modal.querySelectorAll('[data-item]'); if(!rows.length||modal.querySelector('.order-item-picker'))return; const picker=document.createElement('div'); picker.className='order-item-picker'; picker.innerHTML=`<div class="picker-row"><select aria-label="Selecione um prato" class="item-select"><option value="">Selecione um prato</option>${[...rows].map((input,i)=>`<option value="${i}">${safe(input.closest('.order-item').querySelector('b')?.textContent||'Item')}</option>`).join('')}</select><input class="item-quantity" type="number" min="1" max="20" value="1" aria-label="Quantidade"><button class="button primary add-item" type="button">Adicionar item</button></div><div class="selected-items" aria-live="polite">Nenhum item adicionado</div>`; const list=modal.querySelector('.order-items'); list.hidden=true; list.before(picker); const select=picker.querySelector('.item-select'); const quantity=picker.querySelector('.item-quantity'); const summary=picker.querySelector('.selected-items'); picker.querySelector('.add-item').onclick=()=>{if(select.value==='')return;const input=rows[Number(select.value)];input.value=String(Math.min(20,Number(input.value||0)+Number(quantity.value||1)));summary.textContent=[...rows].map((row)=>Number(row.value)>0?`${row.value}x ${row.closest('.order-item').querySelector('b')?.textContent||'Item'}`:'').filter(Boolean).join(' · ')||'Nenhum item adicionado';select.value='';quantity.value='1';}; };
new MutationObserver((mutations)=>mutations.forEach((mutation)=>mutation.addedNodes.forEach((node)=>{if(node.nodeType===1&&node.classList.contains('order-modal-backdrop'))setupItemSelect(node);}))).observe(document.body,{childList:true});
const refreshSelected = (picker) => { const summary=picker.querySelector('.selected-items'); const rows=picker.closest('.order-modal').querySelectorAll('[data-item]'); const selected=[...rows].map((row,i)=>({row,i,name:row.closest('.order-item').querySelector('b')?.textContent||'Item',qty:Number(row.value)})).filter(x=>x.qty>0); summary.innerHTML=selected.length?selected.map(x=>`<span class="selected-chip">${x.qty}x ${safe(x.name)} <button type="button" class="remove-selected" data-index="${x.i}" aria-label="Remover ${safe(x.name)}">×</button></span>`).join(''):'Nenhum item adicionado'; summary.querySelectorAll('.remove-selected').forEach((button)=>button.onclick=()=>{rows[Number(button.dataset.index)].value='0';refreshSelected(picker);}); };
document.addEventListener('click',(event)=>{if(event.target.closest('.add-item'))setTimeout(()=>{const picker=event.target.closest('.order-item-picker');if(picker)refreshSelected(picker);},0);});
